name: Python package
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install dev dependencies
        run:  pip install -r requirements_test.txt
      - name: Run Linter
        run:  pip install flake8
              flake8
      - name: Run Vulture
        run:  pip install vulture
               vulture .
      - name: Run tests
        run:  pip install pytest
              pytest


